### ISSUE TITLE
C stack usage too close to the limit

### ISSUE THREAD

**Issue by Sjoerd-dev** [castoredc/castoRedc#16]
Hi friends, 

I have been working with the package since November 2020 and was able to help a few colleagues in Amsterdam with designing eCRFs and connecting the database with R. Today I ran into an annoying problem using R version 4.0.4 with castoRedc 1.03. When retrieving 
```
studydata         <-  
  castor_api$getStudyData(InterestingStudy) %>% 
  tibble()   
```
the following error returns: `Error: C stack usage  7955504 is too close to the limit`

The process behind this command is finite, while this error mostly arrises during infinite commands? 
I have tried increasing the memory allocation using answer provided in this thread: https://stackoverflow.com/questions/14719349/error-c-stack-usage-is-too-close-to-the-limit

```
> Cstack_info()
        size    current  direction eval_depth 
7953612      13552          1          2 
```
The problem does not emerge when using a Windows based computer. (please don't make fun of me)

As far as I know, the Castor study currently includes 1835 variables across 25 participants. 

Hope somebody is able to help with this problem. 

Best,
Sjoerd

**Comment by Sjoerd-dev** [comment]
Little update:

Doesn't work on updated versions either.
```
R version 4.1.2 (2021-11-01)
castoRedc Version: 1.0.5 (Packaged: 2022-02-17)
```

**Comment by Sjoerd-dev** [comment]
Another update:

Also happening on Windows computers... 
We can't access our study data anymore.

Hope somebody is able to point me to a solution. :)

**Comment by reiniervlinschoten** [comment]
Hi Sjoerd,

- What happens if you try to load another study through the Castor API?
- Are you using RStudio locally on your pc or Rstudio Server?
- Have you tried increasing the stack size according to the stack overflow link?

- If you want, you could try using my package which uses Python on the background to import study data: https://github.com/reiniervlinschoten/castoredc_api-R, however I understand if you'd rather use a native R solution, so lets see if we can figure this out.

**Comment by n-ds** [comment]
Same problem here, issue dwindled down to the following line: https://github.com/castoredc/castoRedc/blob/master/R/CastorData.R#L430

**Comment by reiniervlinschoten** [comment]
Hi all,

Working on this package, and haven't ran into this issue myself.
Did have this issue on an Ubuntu Server with RStudio Server and another package, but there the issue was that the allowed stack size for the RStudio Server process had to be increased.

This issue is now about a year old, not reproducible, and likely not a problem with the package.
Will leave it open for two weeks and if no response, will close it. Is that okay @martijnkersloot?

**Comment by martijnkersloot** [comment]
Totally fine, thanks @reiniervlinschoten!
